### ISSUE TITLE
"photonen abfeuern" does not flash camera light on nexus5/android 4.4.4

### ISSUE THREAD

**Issue by bronsen** [c-base/c-beam-droid#8]
When shooting photons while the camera is deactivated the flash light is not triggered.

After activating the camera, the flashlight is turned on and another photon shot is needed to turn the light off again. However, this does not happen reliably: sometimes it needs several shots with activated camera for the light to be turned on.

**Comment by cmile** [comment]
a new version has been published today, does this still occur with that version?

**Comment by bronsen** [comment]
Can't say: the nexus 5 is gone
