### ISSUE TITLE
make c-beam-droid available in F-droid

### ISSUE THREAD

**Issue by c-MM** [c-base/c-beam-droid#9]
Offer the app on f-droid for those without an google-account.

**Comment by cmile** [comment]
c-beam was initially licensed with the WTF-PL, is GPLv3 required for fdroid? I would rather keep WTF-PL if possible

**Comment by ligi** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/2956

**Comment by ligi** [comment]
the MR was just merged :tada:

**Comment by ligi** [comment]
now build:

https://f-droid.org/packages/org.c_base.c_beam/
